# Example Compose Farm configuration
# Copy to ~/.config/compose-farm/compose-farm.yaml or ./compose-farm.yaml

compose_dir: /opt/compose

hosts:
  # Full form with all options
  server-1:
    address: 192.168.1.10
    user: docker
    port: 22

  # Short form (just address, user defaults to current user)
  server-2: 192.168.1.11

  # Local execution (no SSH)
  local: localhost

services:
  # Map service names to hosts
  # Compose file expected at: {compose_dir}/{service}/compose.yaml
  plex: server-1
  jellyfin: server-2
  sonarr: server-1
  radarr: server-2
